using FinanceConnect.Client.Services;
using FinanceConnect.Client.Shared;
using FinanceConnect.Client.ViewModels;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using System.Linq.Expressions;
using System.Reflection;
using static FinanceConnect.Client.Data.MasterDataIds;

namespace FinanceConnect.Client.Pages.TransactionManagement.FinancialTransactions
{
    public partial class AddFinancialTransaction
    {
        private EditContext _editContext = default!;

        [Inject] MasterDataService MasterDataService { get; set; } = default!;
        [Inject] FinancialTransactionService TxService { get; set; } = default!;
        [Inject] TransactionStatusService TransactionStatusService { get; set; } = default!;

        [Inject] NavigationManager Nav { get; set; } = default!;
        [Inject] IJSRuntime JS { get; set; } = default!;
        [Inject] ToastService ToastService { get; set; } = default!;

        [Parameter] public Guid? Id { get; set; }

        FinancialTransactionModel transaction = new();
        //List<TransactionLineModel> TransactionLines = new();

        List<CompanyModel> Companies = new();
        CompanyModel selectedCompany = new();
        List<CurrencyModel> Currencies = new();
        List<BranchModel> FilteredBranches = new();
        List<TransactionTypeModel> TransactionTypes = new();
        bool IsInitializing = true;
        decimal ExchangeRate = 1;

        bool OwnershipTouched = false;
        bool ClassificationTouched = false;
        bool DatesTouched = false;
        bool CurrencyTouched = false;
        bool NarrationTouched = false;
        bool AuditTouched = false;
        List<TransactionStatusModel> Status = new();
        Guid TenantId = Guid.Parse("11111111-1111-1111-1111-111111111111");
        RichTextEditor? _narrationEditor;
        void TouchOwnership() => OwnershipTouched = true;
        void TouchClassification() => ClassificationTouched = true;
        void TouchDates() => DatesTouched = true;
        void TouchCurrency() => CurrencyTouched = true;
        void TouchNarration() => NarrationTouched = true;
        void TouchAudit() => AuditTouched = true;

        bool ShowOwnership = true;
        bool ShowClassification = false;
        bool ShowDates = false;
        bool ShowCurrency = false;
        bool ShowNarration = false;
        bool ShowLines = false;
        bool ShowAudit = false;

        bool IsEdit => Id.HasValue;
        bool IsEditCurrency = false;
        bool IsLocked => transaction.Status == "Posted" || transaction.Status == "Reversed" || transaction.Status == "Submitted";

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            await JS.InvokeVoidAsync("initFeatherIcons");
        }

        protected override void OnInitialized()
        {
            Companies = TxService.GetCompanies();
            Currencies = MasterDataService.GetAllCurrencies();
            Status = TransactionStatusService.GetAll(TenantId);
            if (IsEdit)
            {
                var existing = TxService.GetById(Id!.Value);
                if (existing != null)
                {
                    FilteredBranches = TxService.GetBranchesByCompany(existing.CompanyId);
                    TransactionTypes = TxService.GetTransactionTypesByCompany(existing.CompanyId);
                    selectedCompany = TxService.GetCompanies().FirstOrDefault(c => c.Id == existing.CompanyId);
                    transaction = new FinancialTransactionModel
                    {
                        FinancialTransactionId = existing.FinancialTransactionId,
                        TenantId = existing.TenantId,

                        CompanyId = existing.CompanyId,
                        BranchId = existing.BranchId,

                        TransactionTypeId = existing.TransactionTypeId,
                        TransactionTypeName = existing.TransactionTypeName,

                        DocumentNo = existing.DocumentNo,
                        SourceModule = existing.SourceModule,
                        SourceDocumentId = existing.SourceDocumentId,
                        SourceDocumentNo = existing.SourceDocumentNo,

                        TransactionDate = existing.TransactionDate,
                        AccountingPeriod = existing.AccountingPeriod,
                        AccountingPeriodId = existing.AccountingPeriodId,
                        CurrencyId = existing.CurrencyId,
                        TransactionAmount = existing.TransactionAmount,
                        BaseAmount = existing.BaseAmount,
                        Narration = existing.Narration,

                        Status = existing.Status,

                        IsAutoGenerated = existing.IsAutoGenerated,
                        IsReversal = existing.IsReversal,
                        ReversalOfTransactionId = existing.ReversalOfTransactionId,

                        SubmittedAt = existing.SubmittedAt,
                        ApprovedAt = existing.ApprovedAt,
                        PostedAt = existing.PostedAt,

                        IsActive = existing.IsActive,

                        CreatedAt = existing.CreatedAt,
                        CreatedBy = existing.CreatedBy,
                        UpdatedAt = existing.UpdatedAt
                    };

                    IsInitializing = false;
                }
            }

            else
            {
                transaction = new FinancialTransactionModel
                {
                    FinancialTransactionId = Guid.NewGuid(),
                    DocumentNo = $"DRAFT-{DateTime.UtcNow:yyyyMMddHHmmss}",
                };
            }

            _editContext = new EditContext(transaction);
        }


        private string GetValidationClass(Expression<Func<object>> field)
        {
            if (_editContext == null)
                return string.Empty;

            var fieldIdentifier = FieldIdentifier.Create(field);

            var hasError = _editContext.GetValidationMessages(fieldIdentifier).Any();
            var isModified = _editContext.IsModified(fieldIdentifier);

            if (hasError)
                return "is-invalid";

            if (isModified)
                return "is-valid";

            return string.Empty;
        }

        void OnCompanyChanged()
        {
            selectedCompany = TxService.GetCompanies().FirstOrDefault(c => c.Id == transaction.CompanyId);
            FilteredBranches = TxService.GetBranchesByCompany(transaction.CompanyId);
            TransactionTypes = TxService.GetTransactionTypesByCompany(transaction.CompanyId);
            if (transaction.TransactionDate.HasValue)
            {
                try
                {
                    var period = TxService.GetAccountingPeriodByDate(transaction);
                    transaction.AccountingPeriod = period.PeriodName ?? "-";
                    transaction.AccountingPeriodId = period.Id;
                }
                catch (Exception e)
                {
                    transaction.AccountingPeriod = "-";
                    transaction.AccountingPeriodId = null;
                    ToastService.ShowError(e.Message);
                }
            }


        }

        void OnTypeChanged()
        {
            var type = TransactionTypes
                .FirstOrDefault(t => t.TransactionTypeId == transaction.TransactionTypeId);

            transaction.TransactionTypeName = type?.Name ?? "";
        }

        void ResolveAccountingPeriod()
        {
            if (!transaction.TransactionDate.HasValue)
            {
                transaction.AccountingPeriod = "-";
                transaction.AccountingPeriodId = null;
                return;
            }
            if (!transaction.CompanyId.HasValue)
            {
                ToastService.ShowError("Company is required");
                return;
            }
            try
            {
                var period = TxService.GetAccountingPeriodByDate(transaction);
                transaction.AccountingPeriod = period.PeriodName ?? "-";
                transaction.AccountingPeriodId = period.Id;
            }
            catch (Exception e)
            {
                transaction.AccountingPeriod = "-";
                transaction.AccountingPeriodId = null;
                ToastService.ShowError(e.Message);
            }

        }

        void RecalculateBase()
        {
            transaction.BaseAmount =
                Math.Round(transaction.TransactionAmount * ExchangeRate, 2);
        }

        // WORKFLOW ACTIONS
        void SubmitTx()
        {
            TxService.Submit(transaction.FinancialTransactionId);
            ToastService.ShowSuccess("Transaction submitted for approval");
            Nav.NavigateTo("/financial-transactions");
        }

        void ApproveTx()
        {
            TxService.Approve(transaction.FinancialTransactionId);
            ToastService.ShowSuccess("Transaction approved");
            Nav.NavigateTo("/financial-transactions");
        }

        void PostTx()
        {
            TxService.Post(transaction.FinancialTransactionId);
            ToastService.ShowSuccess("Transaction posted to ledger");
            Nav.NavigateTo("/financial-transactions");
        }

        void ReverseTx()
        {
            TxService.Reverse(transaction.FinancialTransactionId);
            ToastService.ShowSuccess("Reversal transaction created");
            Nav.NavigateTo("/financial-transactions");
        }

        // SAVE
        async Task Save()
        {
            if (!transaction.AccountingPeriodId.HasValue)
            {
                ToastService.ShowError("Valid accounting period required");
                return;
            }
            var type = TransactionTypes.FirstOrDefault(t => t.TransactionTypeId == transaction.TransactionTypeId);
            try
            {
                if (IsEdit)
                {
                    TxService.Update(transaction);
                    ToastService.ShowSuccess("Transaction updated");
                }
                else
                {
                    transaction.StatusId = Status
                        .FirstOrDefault(s => s.Code == "DRAFT")
                        ?.TransactionStatusId;
                    TxService.Create(transaction,type);
                    ToastService.ShowSuccess("Transaction created as draft");
                }
                Nav.NavigateTo("/financial-transactions");
            }
            catch (Exception e)
            {
                ToastService.ShowError(e.Message);
            }


        }

        private async Task HandleSubmit()
        {
            // Collect Quill editor values before validation
            if (_narrationEditor != null)
                transaction.Narration = await _narrationEditor.GetHtmlAsync();

            if (_editContext.Validate())
            {
                await Save();
                return;
            }

            if (HasOwnershipErrors())
                OpenAccordion("ownership");
            else if (HasClassificationErrors())
                OpenAccordion("classification");
            else if (HasDateErrors())
                OpenAccordion("dates");
            else if (HasCurrencyErrors())
                OpenAccordion("currency");
            else if (HasNarrationErrors())
                OpenAccordion("narration");


            await InvokeAsync(StateHasChanged);
        }


        void ToggleAccordion(string section)
        {
            switch (section)
            {
                case "ownership":
                    ShowOwnership = !ShowOwnership;
                    break;

                case "classification":
                    ShowClassification = !ShowClassification;
                    break;

                case "dates":
                    ShowDates = !ShowDates;
                    break;

                case "currency":
                    ShowCurrency = !ShowCurrency;
                    break;

                case "narration":
                    ShowNarration = !ShowNarration;
                    break;

                case "lines":
                    ShowLines = !ShowLines;
                    break;

                case "audit":
                    ShowAudit = !ShowAudit;
                    break;
            }
        }


        void OpenAccordion(string section)
        {
            switch (section)
            {
                case "ownership":
                    ShowOwnership = true;
                    break;

                case "classification":
                    ShowClassification = true;
                    break;

                case "dates":
                    ShowDates = true;
                    break;

                case "currency":
                    ShowCurrency = true;
                    break;

                case "narration":
                    ShowNarration = true;
                    break;

                case "lines":
                    ShowLines = true;
                    break;

                case "audit":
                    ShowAudit = true;
                    break;
            }
        }



        bool HasOwnershipErrors()
        {
            return transaction.CompanyId == Guid.Empty ||
                   transaction.BranchId == Guid.Empty;
        }

        bool HasClassificationErrors()
        {
            return !transaction.TransactionTypeId.HasValue
                   || transaction.TransactionTypeId == Guid.Empty
                   || string.IsNullOrWhiteSpace(transaction.Status);
        }

        bool HasDateErrors()
        {
            return transaction.TransactionDate == default ||
                   string.IsNullOrWhiteSpace(transaction.AccountingPeriod);
        }

        bool HasCurrencyErrors()
        {
            if (transaction.CurrencyId!=null)
                return true;

            if (transaction.TransactionAmount <= 0 ||
                transaction.BaseAmount <= 0)
                return true;

            return false;
        }

        bool HasNarrationErrors()
        {
            return transaction.Narration?.Length > 1000;
        }


        void BackToList()
        {
            Nav.NavigateTo("/financial-transactions");
        }

        string GetStatusBadge(string status)
        {
            return status switch
            {
                "Draft" => "bg-secondary-transparent text-secondary",
                "Submitted" => "bg-info-transparent text-info",
                "Approved" => "bg-primary-transparent text-primary",
                "Posted" => "bg-success-transparent text-success",
                "Reversed" => "bg-warning-transparent text-warning",
                "Cancelled" => "bg-danger-transparent text-danger",
                _ => "bg-secondary"
            };
        }
    }
}
