using System;
using System.ComponentModel.DataAnnotations;

namespace FinanceConnect.Client.ViewModels
{

    public enum SourceModule
    {
        AP,
        AR,
        BANK,
        EXPENSE,
        ASSET,
        MANUAL    
    }
    public class FinancialTransactionModel
    {

        [Required]
        public Guid FinancialTransactionId { get; set; }

        [Required(ErrorMessage = "Tenant is required.")]
        public Guid TenantId { get; set; }


        [Required(ErrorMessage = "Company is required.")]
        public Guid? CompanyId { get; set; }

        [Required(ErrorMessage = "Branch is mandatory as per posting policy.")]
        public Guid? BranchId { get; set; }


        [Required(ErrorMessage = "Transaction Type is required.")]
        public Guid? TransactionTypeId { get; set; }

        [Required]
        [StringLength(150)]
        public string TransactionTypeName { get; set; } = "";

        [Required(ErrorMessage = "Transaction status is required.")]
        [StringLength(30)]
        public string Status { get; set; } = "Draft";
        // Draft / Submitted / Approved / Posted / Reversed / Cancelled

        public Guid? StatusId { get; set; }

        [Required(ErrorMessage = "Document number cannot exceed 50 characters.")]
        [StringLength(50)]
        public string? DocumentNo { get; set; }


        public Guid DocumentNumberSeriesId { get; set; }

        [Required(ErrorMessage = "Transaction date is required.")]
        public DateTime? TransactionDate { get; set; }

        public string AccountingPeriod { get; set; } = "";

        [Required(ErrorMessage = "Accounting period is required.")]
        public Guid? AccountingPeriodId { get; set; }

        public DateTime? PostingDate { get; set; }


        [Required(ErrorMessage = "Currency is required.")]
        public Guid? CurrencyId { get; set; }

        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Transaction amount must be greater than zero.")]
        public decimal TransactionAmount { get; set; }

        [Required()]
        [Range(0.01, double.MaxValue, ErrorMessage = "Base amount must be greater than zero.")]
        public decimal BaseAmount { get; set; }


        [Required(ErrorMessage = "Source module is required.")]
        public SourceModule SourceModule { get; set; } = SourceModule.MANUAL;

        [Required(ErrorMessage = "Source document reference is required.")]
        public Guid SourceDocumentId { get; set; }

        [StringLength(50, ErrorMessage = "Source reference number cannot exceed 50 characters.")]
        public string? SourceDocumentNo { get; set; }


        [StringLength(1000, ErrorMessage = "Narration cannot exceed 1000 characters.")]
        public string? Narration { get; set; }

        public bool IsAutoGenerated { get; set; } = false;

        public bool IsReversal { get; set; } = false;

        public Guid? ReversalOfTransactionId { get; set; }

        public DateTime? SubmittedAt { get; set; }

        [StringLength(100)]
        public string? SubmittedBy { get; set; }

        public DateTime? ApprovedAt { get; set; }

        [StringLength(100)]
        public string? ApprovedBy { get; set; }

        public DateTime? PostedAt { get; set; }

        [StringLength(100)]
        public string? PostedBy { get; set; }

        public bool IsActive { get; set; } = true;


        [Required]
        public DateTime CreatedAt { get; set; }

        [StringLength(100)]
        public string CreatedBy { get; set; } = "system";

        public DateTime? UpdatedAt { get; set; }

        [StringLength(100)]
        public string? UpdatedBy { get; set; }


        [Timestamp]
        public byte[]? RowVersion { get; set; }

        public bool IsDeleted { get; set; } = false;

        public DateTime? DeletedAt { get; set; }

        [StringLength(100)]
        public string? DeletedBy { get; set; }


        public bool IsDraft => Status == "Draft";
        public bool IsPosted => Status == "Posted";
        public bool IsApproved => Status == "Approved";
        public bool IsSubmitted => Status == "Submitted";
        public bool IsCancelled => Status == "Cancelled";
        public bool IsReversed => Status == "Reversed";
    }

    public class FinancialTransactionStatistics
    {
        public int TotalStatements { get; set; }
        public int UploadedStatements { get; set; }
        public int ReadyForReconciliationStatements { get; set; }
        public int LockedStatements { get; set; }
        public int ArchivedStatements { get; set; }
        public int SupersededStatements { get; set; }

    }
    
}
