using System.ComponentModel.DataAnnotations;

namespace FinanceConnect.Client.ViewModels
{
    #region Model #42: VendorAging

    /// <summary>
    /// Model #42: VendorAging – AP Time-based outstanding analysis snapshot.
    /// Groups vendor's open payables into aging buckets (Current, 0-30, 31-60, 61-90, 91-120, 121-180, 181-365, 365+).
    /// Used for payment prioritization, month-end AP review, cashflow planning, and audit evidence.
    /// Snapshots are immutable once finalized.
    /// </summary>
    public class VendorAgingViewModel
    {
        // Section 1: Core Snapshot Identity

        /// <summary>PK - VendorAgingId - hidden in UI</summary>
        public Guid VendorAgingId { get; set; } = Guid.NewGuid();

        /// <summary>Tenant identifier - hidden in UI</summary>
        [Required(ErrorMessage = "Tenant is required")]
        public Guid TenantId { get; set; } = Guid.Parse("00000000-0000-0000-0000-000000000001");

        /// <summary>FK → Company - hidden in UI</summary>
        [Required(ErrorMessage = "Company is required")]
        public Guid CompanyId { get; set; }
        public string? CompanyName { get; set; }

        /// <summary>FK → Branch (Optional dimension) - filterable</summary>
        public Guid? BranchId { get; set; }
        public string? BranchCode { get; set; }
        public string? BranchName { get; set; }

        /// <summary>As Of Date - date picker for running report</summary>
        [Required(ErrorMessage = "As Of Date is required")]
        public DateTime AsOfDate { get; set; } = DateTime.Today;

        /// <summary>Aging Run Id - groups all rows produced in one run</summary>
        [Required(ErrorMessage = "Aging Run Id is required")]
        public Guid AgingRunId { get; set; } = Guid.NewGuid();

        /// <summary>Run Type - badge (Nightly/OnDemand/MonthEndFinal)</summary>
        [Required(ErrorMessage = "Run Type is required")]
        public string RunType { get; set; } = "";

        /// <summary>Run Status - badge (Started/Completed/Failed/Finalized)</summary>
        [Required(ErrorMessage = "Run Status is required")]
        public string RunStatus { get; set; } = VendorAgingRunStatuses.Started;

        /// <summary>Generated At - datetime (system)</summary>
        public DateTime GeneratedAt { get; set; } = DateTime.Now;

        /// <summary>Generated By - user id (system; for nightly maybe "SYSTEM")</summary>
        public Guid? GeneratedByUserId { get; set; }
        public string? GeneratedByUserName { get; set; }

        // Section 2: Vendor + Currency Dimension (stored at header level for filtering)

        /// <summary>FK → CurrencyMaster - display/filter</summary>
        [Required(ErrorMessage = "Currency is required")]
        public Guid CurrencyId { get; set; }
        public string? CurrencyCode { get; set; }
        public string? CurrencyName { get; set; }

        /// <summary>Base Currency Id (Optional) - for multi-currency conversion</summary>
        public Guid? BaseCurrencyId { get; set; }
        public string? BaseCurrencyCode { get; set; }

        /// <summary>Exchange Rate Snapshot (Optional) - for conversion to base</summary>
        public decimal? ExchangeRateSnapshot { get; set; }

        // Section 3: Include Credits Toggle
        /// <summary>Include Open Credits toggle - recommended default ON</summary>
        public bool IncludeOpenCredits { get; set; } = true;

        // Section 4: Aggregate Totals (System Derived)

        /// <summary>Total Outstanding Amount - sum of all overdue + current buckets (gross)</summary>
        public decimal TotalOutstandingAmount { get; set; } = 0;

        /// <summary>Record Count - Vendors</summary>
        public int RecordCountVendors { get; set; } = 0;

        /// <summary>Record Count - Bills</summary>
        public int RecordCountBills { get; set; } = 0;

        // Section 5: Child Collections

        /// <summary>Vendor Summary Rows - one row per vendor</summary>
        public List<VendorAgingVendorRowViewModel> VendorRows { get; set; } = new();

        /// <summary>Bill Detail Rows - drilldown per bill (optional but recommended)</summary>
        public List<VendorAgingBillRowViewModel> BillRows { get; set; } = new();

        // Section 6: System Audit Fields

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? UpdatedBy { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
        public bool IsDeleted { get; set; } = false;
        public DateTime? DeletedAt { get; set; }
        public string? DeletedBy { get; set; }

        // Helper Methods

        /// <summary>Recalculate totals from vendor rows</summary>
        public void RecalculateTotals()
        {
            TotalOutstandingAmount = VendorRows.Sum(r => r.TotalOutstandingAmount);
            RecordCountVendors = VendorRows.Count;
            RecordCountBills = BillRows.Count;
        }

        /// <summary>Check if snapshot is completed</summary>
        public bool IsCompleted => RunStatus == VendorAgingRunStatuses.Completed || RunStatus == VendorAgingRunStatuses.Finalized;

        /// <summary>Check if snapshot can be regenerated</summary>
        public bool CanRegenerate => RunStatus == VendorAgingRunStatuses.Failed;

        /// <summary>Check if snapshot is finalized (immutable)</summary>
        public bool IsFinalized => RunStatus == VendorAgingRunStatuses.Finalized;
    }

    #endregion

    #region VendorAgingVendorRow

    /// <summary>
    /// Vendor Summary Row - one row per vendor in the aging snapshot.
    /// Contains bucket totals and metrics for payment prioritization.
    /// </summary>
    public class VendorAgingVendorRowViewModel
    {
        /// <summary>PK - VendorAgingVendorRowId - hidden</summary>
        public Guid VendorAgingVendorRowId { get; set; } = Guid.NewGuid();

        /// <summary>FK → VendorAging - hidden</summary>
        [Required]
        public Guid VendorAgingId { get; set; }

        /// <summary>FK → Vendor - drill-down anchor</summary>
        [Required(ErrorMessage = "Vendor is required")]
        public Guid VendorId { get; set; }

        /// <summary>Vendor Code Snapshot - read-only - preserve identity as-of snapshot</summary>
        [StringLength(30)]
        public string? VendorCodeSnapshot { get; set; }

        /// <summary>Vendor Name Snapshot - read-only - preserve identity as-of snapshot</summary>
        [StringLength(200)]
        public string? VendorNameSnapshot { get; set; }

        /// <summary>FK → CurrencyMaster - display/filter</summary>
        [Required(ErrorMessage = "Currency is required")]
        public Guid CurrencyId { get; set; }
        public string? CurrencyCode { get; set; }

        // Section 3: Aging Amount Buckets (System Derived) - All amounts: decimal(18,2) and read-only

        /// <summary>Total Outstanding Amount - Sum of all overdue + current buckets (gross)</summary>
        public decimal TotalOutstandingAmount { get; set; } = 0;

        /// <summary>Current Not Due Amount - DueDate > AsOfDate</summary>
        public decimal CurrentNotDueAmount { get; set; } = 0;

        /// <summary>Bucket 0-30 Days Amount</summary>
        public decimal Bucket_0_30 { get; set; } = 0;

        /// <summary>Bucket 31-60 Days Amount</summary>
        public decimal Bucket_31_60 { get; set; } = 0;

        /// <summary>Bucket 61-90 Days Amount</summary>
        public decimal Bucket_61_90 { get; set; } = 0;

        /// <summary>Bucket 91-120 Days Amount</summary>
        public decimal Bucket_91_120 { get; set; } = 0;

        /// <summary>Bucket 121-180 Days Amount</summary>
        public decimal Bucket_121_180 { get; set; } = 0;

        /// <summary>Bucket 181-365 Days Amount</summary>
        public decimal Bucket_181_365 { get; set; } = 0;

        /// <summary>Bucket 366+ Days Amount</summary>
        public decimal Bucket_366_Plus { get; set; } = 0;

        /// <summary>Overdue Total Amount (Derived) - TotalOutstanding − CurrentNotDue</summary>
        public decimal OverdueTotalAmount => TotalOutstandingAmount - CurrentNotDueAmount;

        // Section 4: Credits / Advances / Net Payable (Policy Based)

        /// <summary>Open Credit Amount - unapplied VendorCreditNotes + advances</summary>
        public decimal OpenCreditAmount { get; set; } = 0;

        /// <summary>Net Payable Amount (Derived) - TotalOutstanding − OpenCredit</summary>
        public decimal NetPayableAmount { get; set; } = 0;

        /// <summary>Credit Balance Excess Amount (Optional) - max(OpenCredit − TotalOutstanding, 0)</summary>
        public decimal CreditBalanceExcessAmount { get; set; } = 0;

        // Section 5: Diagnostics / Drilldown Metrics

        /// <summary>Open Document Count - count of open bills/notes contributing</summary>
        public int OpenDocumentCount { get; set; } = 0;

        /// <summary>Oldest Due Date - date of oldest unpaid due</summary>
        public DateTime? OldestDueDate { get; set; }

        /// <summary>Latest Bill Date - latest bill posting date contributing</summary>
        public DateTime? LatestBillDate { get; set; }

        /// <summary>Latest Payment Date - latest payment posting date affecting vendor</summary>
        public DateTime? LatestPaymentDate { get; set; }

        /// <summary>Reconciliation Status - (Matched/MinorDifference/Mismatch)</summary>
        [StringLength(20)]
        public string ReconciliationStatus { get; set; } = VendorAgingReconciliationStatuses.Matched;

        /// <summary>Reconciliation Difference Amount - decimal(18,2)</summary>
        public decimal ReconciliationDifferenceAmount { get; set; } = 0;

        // System Audit Fields
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? UpdatedBy { get; set; }

        // Helper: Validate that bucket sum equals total
        public bool ValidateBucketSum()
        {
            var sum = CurrentNotDueAmount + Bucket_0_30 + Bucket_31_60 + Bucket_61_90 + 
                      Bucket_91_120 + Bucket_121_180 + Bucket_181_365 + Bucket_366_Plus;
            return Math.Abs(sum - TotalOutstandingAmount) < 0.01m;
        }
    }

    #endregion

    #region VendorAgingBillRow

    /// <summary>
    /// Bill Detail Row - drilldown per bill in the aging snapshot.
    /// Shows bill-level aging details for audit and verification.
    /// </summary>
    public class VendorAgingBillRowViewModel
    {
        /// <summary>PK - VendorAgingBillRowId - hidden</summary>
        public Guid VendorAgingBillRowId { get; set; } = Guid.NewGuid();

        /// <summary>FK → VendorAging - hidden</summary>
        [Required]
        public Guid VendorAgingId { get; set; }

        /// <summary>FK → Vendor - read-only</summary>
        [Required]
        public Guid VendorId { get; set; }

        /// <summary>FK → VendorBill - read-only link</summary>
        [Required(ErrorMessage = "Vendor Bill is required")]
        public Guid VendorBillId { get; set; }

        /// <summary>Bill Number Snapshot - string - read-only</summary>
        [StringLength(40)]
        public string? BillNumberSnapshot { get; set; }

        /// <summary>Bill Date Snapshot - date - read-only</summary>
        public DateTime BillDateSnapshot { get; set; }

        /// <summary>Due Date Snapshot - date - read-only</summary>
        public DateTime DueDateSnapshot { get; set; }

        /// <summary>Outstanding Amount - decimal(18,2) - read-only</summary>
        public decimal OutstandingAmount { get; set; } = 0;

        /// <summary>Overdue Days - int - read-only - max(0, AsOfDate - DueDate)</summary>
        public int OverdueDays { get; set; } = 0;

        /// <summary>Bucket Code - string/enum - badge</summary>
        [Required]
        [StringLength(20)]
        public string BucketCode { get; set; } = VendorAgingBucketCodes.CurrentNotDue;

        /// <summary>Last Payment Date Snapshot (Optional) - date - read-only</summary>
        public DateTime? LastPaymentDateSnapshot { get; set; }

        /// <summary>Source Document Type - enum (Bill/DebitNote/CreditNote/Adjustment) - read-only</summary>
        [StringLength(30)]
        public string SourceDocumentType { get; set; } = VendorAgingSourceDocumentTypes.Bill;

        // System Audit Fields
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public string? CreatedBy { get; set; }
    }

    #endregion

    #region VendorAging-related Enums and Static Classes

    /// <summary>Vendor Aging Run Types</summary>
    public static class VendorAgingRunTypes
    {
        public const string Nightly = "Nightly";
        public const string OnDemand = "OnDemand";
        public const string MonthEndFinal = "MonthEndFinal";
        public static readonly string[] All = new[] { Nightly, OnDemand, MonthEndFinal };

        public static string GetDisplayName(string runType) => runType switch
        {
            Nightly => "Nightly",
            OnDemand => "On-Demand",
            MonthEndFinal => "Month-End Final",
            _ => runType
        };
    }

    /// <summary>Vendor Aging Run Statuses</summary>
    public static class VendorAgingRunStatuses
    {
        public const string Started = "Started";
        public const string Completed = "Completed";
        public const string Failed = "Failed";
        public const string Finalized = "Finalized";
        public static readonly string[] All = new[] { Started, Completed, Failed, Finalized };

        public static string GetDisplayName(string status) => status switch
        {
            Started => "Started",
            Completed => "Completed",
            Failed => "Failed",
            Finalized => "Finalized",
            _ => status
        };
    }

    /// <summary>Vendor Aging Bucket Codes - extended for AP (8 buckets)</summary>
    public static class VendorAgingBucketCodes
    {
        public const string CurrentNotDue = "Current";
        public const string Days0To30 = "0-30";
        public const string Days31To60 = "31-60";
        public const string Days61To90 = "61-90";
        public const string Days91To120 = "91-120";
        public const string Days121To180 = "121-180";
        public const string Days181To365 = "181-365";
        public const string Days366Plus = "365+";
        public static readonly string[] All = new[] { CurrentNotDue, Days0To30, Days31To60, Days61To90, Days91To120, Days121To180, Days181To365, Days366Plus };

        public static string GetDisplayName(string code) => code switch
        {
            CurrentNotDue => "Current (Not Due)",
            Days0To30 => "0-30 Days",
            Days31To60 => "31-60 Days",
            Days61To90 => "61-90 Days",
            Days91To120 => "91-120 Days",
            Days121To180 => "121-180 Days",
            Days181To365 => "181-365 Days",
            Days366Plus => "365+ Days",
            _ => code
        };

        public static string GetBucketCode(int overdueDays)
        {
            if (overdueDays < 0) return CurrentNotDue;
            if (overdueDays <= 30) return Days0To30;
            if (overdueDays <= 60) return Days31To60;
            if (overdueDays <= 90) return Days61To90;
            if (overdueDays <= 120) return Days91To120;
            if (overdueDays <= 180) return Days121To180;
            if (overdueDays <= 365) return Days181To365;
            return Days366Plus;
        }
    }

    /// <summary>Vendor Aging Source Document Types</summary>
    public static class VendorAgingSourceDocumentTypes
    {
        public const string Bill = "Bill";
        public const string DebitNote = "DebitNote";
        public const string CreditNote = "CreditNote";
        public const string Adjustment = "Adjustment";
        public static readonly string[] All = new[] { Bill, DebitNote, CreditNote, Adjustment };

        public static string GetDisplayName(string type) => type switch
        {
            Bill => "Vendor Bill",
            DebitNote => "Debit Note",
            CreditNote => "Credit Note",
            Adjustment => "AP Adjustment",
            _ => type
        };
    }

    /// <summary>Vendor Aging Reconciliation Statuses</summary>
    public static class VendorAgingReconciliationStatuses
    {
        public const string Matched = "Matched";
        public const string MinorDifference = "MinorDifference";
        public const string Mismatch = "Mismatch";
        public static readonly string[] All = new[] { Matched, MinorDifference, Mismatch };

        public static string GetDisplayName(string status) => status switch
        {
            Matched => "Matched",
            MinorDifference => "Minor Difference",
            Mismatch => "Mismatch",
            _ => status
        };
    }

    #endregion
}
