using FinanceConnect.Client.Services;
using FinanceConnect.Client.ViewModels;
using System.ComponentModel.Design;
using System.Data.Common;
using System.Net.NetworkInformation;
using System.Transactions;
using static FinanceConnect.Client.Data.MasterDataIds;

namespace FinanceConnect.Client.Data
{
    public class FinancialTransactionSeedData
    {
        private readonly DocumentNumberSeriesService _docNumSeriesService;
        private readonly FiscalYearService _fiscalYearService;
        private readonly AccountingPeriodService _accPeriodService;
        private readonly TransactionStatusService _transactionStatusService;

        public FinancialTransactionSeedData(DocumentNumberSeriesService documentNumberSeriesService,
            FiscalYearService fiscalYearService,AccountingPeriodService accPeriodService, TransactionStatusService transactionStatusService
            )
        {
            _docNumSeriesService = documentNumberSeriesService;
            _fiscalYearService = fiscalYearService;
            _accPeriodService = accPeriodService;
            _transactionStatusService = transactionStatusService;
        }
        public List<FinancialTransactionModel> Seed(
                List<CompanyModel> companies,
                List<BranchModel> branches,
                List<TransactionTypeModel> types)
        {
            Guid TenantId = Guid.Parse("11111111-1111-1111-1111-111111111111");
            if (!companies.Any())
                throw new InvalidOperationException("No active companies found for transaction seed.");

            if (!branches.Any())
                throw new InvalidOperationException("No branches found for transaction seed.");

            if (!types.Any())
                throw new InvalidOperationException("No active transaction types found for transaction seed.");

            var result = new List<FinancialTransactionModel>();
            var now = DateTime.UtcNow;
            var StatusID = _transactionStatusService.GetAll(TenantId)
                .FirstOrDefault(s => s.Code == "DRAFT")
                ?.TransactionStatusId;

            int globalCounter = 1;

            foreach (var company in companies)
            {
                // Get branches for this company
                var companyBranches = branches
                    .Where(b => b.CompanyId == company.Id && b.Status == "Active")
                    .ToList();

                if (!companyBranches.Any())
                    continue; // Skip companies with no branches

                var branch = companyBranches.First();

                // Use a random active transaction type for realism
                var type = types.FirstOrDefault(t=> t.CompanyId == company.Id);

                // Create 2 transactions per company
                for (int i = 1; i <= 2; i++)
                {
                    var (fy, period) = GetOpenFiscalContext(company.Id, now.AddDays(i));
                    result.Add(new FinancialTransactionModel
                    {
                        FinancialTransactionId = Guid.NewGuid(),
                        TenantId = Guid.Parse("11111111-1111-1111-1111-111111111111"),

                        CompanyId = company.Id,
                        BranchId = branch.Id,

                        TransactionTypeId = type.TransactionTypeId,
                        TransactionTypeName = type.Name,

                        DocumentNo = _docNumSeriesService.Generate(
                        type.DocumentNumberSeriesId.Value,
                        now.AddDays(-i),
                        company.Id,
                        branch.Id),

                        SourceModule = SourceModule.AP,
                        SourceDocumentId = Guid.NewGuid(),
                        SourceDocumentNo = $"SRC-{globalCounter:0000}",

                        TransactionDate = now.AddDays(-i),
                        AccountingPeriod = period.PeriodName,
                        AccountingPeriodId = period.Id,

                        CurrencyId = company.BaseCurrencyId,
                        TransactionAmount = 1000 * globalCounter,
                        BaseAmount = 1000 * globalCounter,

                        Status = "Draft",
                        StatusId = StatusID,
                        IsAutoGenerated = false,
                        IsReversal = false,

                        CreatedAt = now.AddDays(-i),
                        CreatedBy = "seed"
                    });

                    globalCounter++;
                }
            }

            return result;
        }


        private (FiscalYearModel fy, AccountingPeriodModel period)
          GetOpenFiscalContext(Guid companyId, DateTime postingDate)
        {
            var fy = _fiscalYearService.GetAll().FirstOrDefault(x =>
                x.CompanyId == companyId &&
                x.StartDate <= postingDate &&
                x.EndDate >= postingDate &&
                (x.Status == FiscalYearStatus.Open || x.Status == FiscalYearStatus.SoftClosed));

            if (fy == null)
                throw new InvalidOperationException(
                    $"No open fiscal year found for company {companyId} on {postingDate:yyyy-MM-dd}.");

            var period = _accPeriodService.GetAll().FirstOrDefault(p =>
                p.CompanyId == companyId &&
                p.FiscalYearId == fy.Id &&
                p.StartDate <= postingDate &&
                p.EndDate >= postingDate &&
                (p.Status == AccountingPeriodStatus.Open || p.Status == AccountingPeriodStatus.SoftClosed));

            if (period == null)
                throw new InvalidOperationException(
                    $"No open accounting period found for company {companyId} on {postingDate:yyyy-MM-dd}.");

            return (fy, period);
        }
    }
}
